### ISSUE TITLE
Short description issue

### ISSUE THREAD

**Issue by drgrigg** [johnrambow/henry-adams_democracy#4]
I _think_ but because I'm Australian I'm not sure, that it should be "Washington DC" rather than "Washington, DC". I don't think the comma is needed.

**Comment by johnrambow** [comment]
This should be OK as is -- the DC part is treated like a state, so it's set off by commas. (And arguably we could just call the place Washington, since it is pretty clear we are talking about the capital, not the future state.) https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Abbreviations/faq0048.html
